### ISSUE TITLE
Incorrect phone # field types

### ISSUE THREAD

**Issue by bo0ohXae** [kitserve/z-push-roundcube#2]
I setup sync between my android phone and roundcube with z-push.  It seems to work at first, but I noticed that when I enter a contacts mobile number in roundcube, on the phone it shows up incorrectly  as their 'home' number.  If I edit the contact on the phone, and change 'home' -> 'mobile', then in roundcube it changes incorrectly to 'other'.

As far as I can tell, the issue seems to be that z-push-roundcube doesn't know about the phone number type 'mobile' but only 'cell' per the v-card standard.  But neither roundcube, nor android, nor activesync (or at least outlook) seem to call it 'cell', they all use 'mobile' so why follow the v-card standard?

**Comment by kitserve** [comment]
I've experienced the same issue on Windows Phone. You're right, we should be translating 'cell' to 'mobile'. Patches welcome!

**Comment by bo0ohXae** [comment]
FYI I found Microsoft's activesync documentation here https://msdn.microsoft.com/en-us/library/cc425499.aspx
In particular this seems to be the relevant schema https://msdn.microsoft.com/en-us/library/dn338914%28v=exchg.80%29.aspx

Here they call it "MobilePhoneNumber", so not sure if we actually need to call it that, or just "Mobile"?  Depends if z-push already renames the fields I guess.

**Comment by bo0ohXae** [comment]
Well to answer my own question, it seems roundcubecontacts.php line 540 is already doing this:
                                elseif( in_array( 'cell', $tel['type'] ) )
                                {
                                        $message->mobilephonenumber = $tel['val'][0];
                                }

The issue (bug?) actually seems to be with roundcube itself.  When you enter a mobile phone number, it for some reason capitalizes the field type within the database:
TEL;TYPE=CELL:xyz

As a workaround I changed line 540 to read:
elseif( in_array( 'cell', $tel['type'] ) or in_array( 'CELL', $tel['type'] ) ) 

And now its working for me.  I guess ideally it should be a case-insensitive search, but I'm not sure the best way to do that.

**Comment by bo0ohXae** [comment]
Update: rfc2426.txt says
   tel-type     = "HOME" / "WORK" / "PREF" / "VOICE" / "FAX" / "MSG"
                / "CELL" / "PAGER" / "BBS" / "MODEM" / "CAR" / "ISDN"
                / "VIDEO" / "PCS" / iana-token / x-name
        ; Values are case insensitive

So I guess its not a roundcube bug then to use caps.  This plugin just needs to ignore case.

**Comment by kitserve** [comment]
Good find, we'll try to get that ported in shortly.
